name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  version:
    description: 'Cecil version.'
  config:
    description: 'Cecil config.'
  args:
    description: 'Cecil arguments.'
    default: '-vv'
  install_themes:
    description: '"yes" to install theme(s).'
    default: 'yes'
  install_intl:
    description: '"yes" to install INTL extensions.'
    default: 'no'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'composite'
  steps:
    - run: |
        # Download Cecil
        echo "Download Cecil ${{ inputs.version }}"
        if [[ -z "${{ inputs.version }}" ]]; then
          curl -sSOL https://cecil.app/cecil.phar
        else
          curl -sSOL https://cecil.app/download/${{ inputs.version }}/cecil.phar
        fi

        # Install theme(s)
        if [[ -f "composer.json" && $INPUT_INSTALL_THEMES = 'yes' ]]; then
          echo "Install theme(s)"
          #curl -sS https://getcomposer.org/installer | php
          #php composer.phar install --prefer-dist --no-dev --no-progress --no-interaction
          composer install --prefer-dist --no-dev --no-progress --no-interaction
        fi

        # Install INTL extensions
        if [[ $INPUT_INSTALL_INTL = 'yes' ]]; then
          echo "Install INTL extensions"
          apk update > /dev/null
          apk add --no-cache gettext-dev icu-dev > /dev/null
          docker-php-ext-install -j$(nproc) gettext > /dev/null
          docker-php-ext-install -j$(nproc) intl > /dev/null
        fi

        # Run build
        echo "POUET: ${{ inputs.config }}"
        if [[ -z "${{ inputs.config }}" ]]; then
          php cecil.phar build $INPUT_ARGS
        else
          php cecil.phar build $INPUT_ARGS --config=${{ inputs.config }}
        fi
      shell: bash
