name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  arguments:
    description: 'Ceclin CLI arguments.'
    default: '-v'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
    - 'intl'
