name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  version:
    description: 'Cecil version.'
  config:
    description: 'Cecil configuration'
  args:
    description: 'Cecil arguments.'
    default: '-v'
  install_themes:
    description: '"yes" to install theme(s).'
    default: 'yes'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'composite'
  steps:
    - run: |
        # Downloading Cecil
        echo "Downloading Cecil ${{ inputs.version }}"
        if [[ -z "${{ inputs.version }}" ]]; then
          curl -sSOL https://cecil.app/cecil.phar
        else
          curl -sSOL https://cecil.app/download/${{ inputs.version }}/cecil.phar
        fi
        # Installing theme(s)
        if [[ -f "composer.json" && ${{ inputs.install_themes }} = 'yes' ]]; then
          echo "Installing theme(s)"
          composer install --prefer-dist --no-dev --no-progress --no-interaction
        fi
        # Running build
        if [[ -z "${{ inputs.config }}" ]]; then
          php cecil.phar build ${{ inputs.args }}
        else
          php cecil.phar build ${{ inputs.args }} --config=${{ inputs.config }}
        fi
      shell: bash
