name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  version:
    description: 'Cecil version.'
  config:
    description: 'Cecil config.'
  args:
    description: 'Cecil arguments.'
    default: '-v'
  install_themes:
    description: '"yes" to install theme(s).'
    default: 'yes'
  install_intl:
    description: '"yes" to install INTL extensions.'
    default: 'no'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/build.sh
      shell: bash
