name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  args:
    description: 'Cecil arguments.'
    default: '-v'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INTL: ${{ inputs.intl }}
