name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  version:
    description: 'Cecil version.'
  config:
    description: 'Cecil config.'
  args:
    description: 'Cecil arguments.'
    default: '-vv'
  install_themes:
    description: '"yes" to install theme(s).'
    default: 'yes'
  install_intl:
    description: '"yes" to install INTL extensions.'
    default: 'no'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Download Cecil $INPUT_VERSION"
        if [[ -z "$INPUT_VERSION" ]]; then
          curl -sSOL https://cecil.app/cecil.phar
        else
          curl -sSOL https://cecil.app/download/$INPUT_VERSION/cecil.phar
        fi
        if [[ -f "composer.json" && $INPUT_INSTALL_THEMES = 'yes' ]]; then
          echo "Install theme(s)"
          composer install --prefer-dist --no-dev --no-progress --no-interaction
        fi
        if [[ $INPUT_INSTALL_INTL = 'yes' ]]; then
          echo "Install INTL extensions"
          apk update > /dev/null
          apk add --no-cache gettext-dev icu-dev > /dev/null
          docker-php-ext-install -j$(nproc) gettext > /dev/null
          docker-php-ext-install -j$(nproc) intl > /dev/null
        fi
        if [[ -z "$INPUT_CONFIG" ]]; then
          php cecil.phar build $INPUT_ARGS
        else
          php cecil.phar build $INPUT_ARGS --config=$INPUT_CONFIG
        fi
      shell: bash
