name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  version:
    description: 'Cecil version (optional, last version by default).'
  config:
    description: 'Cecil configuration file (optional, `cecil.yml` by default).'
  args:
    description: 'Cecil arguments (optionnal, `-v` by default).'
    default: '-v'
  install_themes:
    description: 'Use "no" to do not install theme(s) (optionnal, `yes` by default).'
    default: 'yes'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'composite'
  steps:
    - run: |
        # Downloading Cecil
        if [[ -z "${{ inputs.version }}" ]]; then
          echo "Downloading Cecil..."
          curl -sSOL https://cecil.app/cecil.phar
        else
          echo "Downloading Cecil ${{ inputs.version }}..."
          curl -sSOL https://cecil.app/download/${{ inputs.version }}/cecil.phar
        fi
        # Installing theme(s)
        if [[ -f "composer.json" && ${{ inputs.install_themes }} = 'yes' ]]; then
          echo "Installing theme(s)..."
          composer install --prefer-dist --no-dev --no-progress --no-interaction --quiet
        fi
        # Running build
        if [[ -z "${{ inputs.config }}" ]]; then
          php cecil.phar build ${{ inputs.args }}
        else
          php cecil.phar build ${{ inputs.args }} --config=${{ inputs.config }}
        fi
        if [ $? == 0 ]
        then
          echo "Site built with Cecil ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
