name: 'Cecil Action'
description: 'Build a Cecil static site.'
author: 'Arnaud Ligny'
inputs: 
  arguments:
    description: 'Cecil arguments.'
    default: '-v'
  intl:
    description: 'Install Intl extensions.'
    default: 'no'
branding:
  icon: 'package'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.intl }}
