name: test

on:
  push:
    branches:
    - master
    - composite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: ./
      with:
        version: '5.55.0'
        args: '-v'
        install_themes: 'yes'
        install_intl: 'yes'
