name: test
on:
  push:
    branches: [main, master]
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create a dummy page
        run: |
          mkdir -p pages
          cat > pages/index.md <<EOL
          This is a test page for the Cecil GitHub Action.
          EOL
      - name: Run Action
        uses: ./
        with:
          version: '8.94.3'
          options: '-vv'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
