name: test

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Create a dummy page
        run: |
          mkdir -p pages
          cat > pages/index.md <<EOL
          Test
          EOL

      - name: Run Action
        uses: ./
        with:
          version: '8.0.0'
          args: '-vv'
          install_themes: 'yes'
