name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Build
        uses: ./
        with:
          version: '7.44.2'
          args: '-vv'
          install_themes: 'yes'
